### ISSUE TITLE
Error log in documentation for progress bar component

### ISSUE THREAD

**Issue by pbugnion** [ASIDataScience/dash-bootstrap-components#70]
The progress bar component occasionally triggers an error -- I think when it's first loaded. This is the stack trace.

```
Traceback (most recent call last):
File "/opt/anaconda/envs/Python3/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
return self.wsgi_app(environ, start_response)
File "/opt/anaconda/envs/Python3/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
response = self.handle_exception(e)
File "/opt/anaconda/envs/Python3/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
reraise(exc_type, exc_value, tb)
File "/opt/anaconda/envs/Python3/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
raise value
File "/opt/anaconda/envs/Python3/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
response = self.full_dispatch_request()
File "/opt/anaconda/envs/Python3/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/opt/anaconda/envs/Python3/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/opt/anaconda/envs/Python3/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
raise value
File "/opt/anaconda/envs/Python3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
rv = self.dispatch_request()
File "/opt/anaconda/envs/Python3/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/opt/anaconda/envs/Python3/lib/python3.6/site-packages/dash/dash.py", line 962, in dispatch
return self.callback_map[target_id]['callback'](*args)
File "/opt/anaconda/envs/Python3/lib/python3.6/site-packages/dash/dash.py", line 902, in add_context
output_value = func(*args, **kwargs)
File "<string>", line 17, in advance_progress

TypeError: unsupported operand type(s) for %: 'NoneType' and 'int'
```

I haven't had time to investigate, but I suspect we don't catch the initial None in the callback.

**Comment by tcbegley** [comment]
Yep, that's exactly the problem. I caught this yesterday as well and tacked a patch on to #58 by setting `n_intervals=0` initially.

**Comment by pbugnion** [comment]
Ah great! Should we close this, then?

**Comment by tcbegley** [comment]
Ah yes, meant to do that after merging.
