### ISSUE TITLE
Documentation does not build on latest dash 

### ISSUE THREAD

**Issue by nadaouk** [ASIDataScience/dash-bootstrap-components#87]
Traceback (most recent call last):
File "run.py", line 3, in <module>
from app import App
File "/project/nadine/dash-bootstrap-components/docs/app.py", line 7, in <module>
from components_page import ComponentsPage
File "/project/nadine/dash-bootstrap-components/docs/components_page/__init__.py", line 1, in <module>
from .page import ComponentsPage  # noqa: F401
File "/project/nadine/dash-bootstrap-components/docs/components_page/page.py", line 5, in <module>
from .alerts_content import content as alerts_content
File "/project/nadine/dash-bootstrap-components/docs/components_page/alerts_content.py", line 3, in <module>
from .api_doc import ApiDoc
File "/project/nadine/dash-bootstrap-components/docs/components_page/api_doc.py", line 4, in <module>
from dash.development.base_component import (
ImportError: cannot import name 'filter_props'

**Comment by tcbegley** [comment]
Thanks for reporting @nadaouk!

**Comment by tcbegley** [comment]
Resolved by #88
